# Generated by Django 2.2 on 2021-06-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charater',
            new_name='Character',
        ),
    ]
